# Generated by Django 3.2.7 on 2022-05-13 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chatapp', '0004_create_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_room',
            old_name='room_name',
            new_name='name',
        ),
    ]
