# Generated by Django 3.2.7 on 2022-05-14 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chatapp', '0006_alter_create_room_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='create_room',
        ),
        migrations.DeleteModel(
            name='room',
        ),
    ]
